function Get-TwitterBlocks_List {

<#
.SYNOPSIS
    Mute, block and report users

.DESCRIPTION
    GET blocks/list
    
    Returns a collection of user objects that the authenticating user is blocking.
    
    Important This method is cursored, meaning your app must make multiple requests in order to receive all blocks correctly. See Using cursors to navigate collections for more details on how cursoring works.

.PARAMETER include_entities
    The entities node will not be included when set to false .

.PARAMETER skip_status
    When set to either true , t or 1 statuses will not be included in the returned user objects.

.PARAMETER cursor
    Causes the list of blocked users to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended users are filtered out after connections are queried. If no cursor is provided, a value of -1 will be assumed, which is the first "page."
The response from the API will include a previous_cursor and next_cursor to allow paging back and forth. See Using cursors to navigate collections for more information.

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/accounts-and-users/mute-block-report-users/api-reference/get-blocks-list

#>
    [CmdletBinding()]
    Param(
        [string]$include_entities,
        [string]$skip_status,
        [string]$cursor
    )
    Begin {

        [string]$Method      = 'GET'
        [string]$Resource    = '/blocks/list'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/blocks/list.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
