function Get-TwitterAccount_Settings {

<#
.SYNOPSIS
    Manage account settings and profile

.DESCRIPTION
    GET account/settings
    
    Returns settings (including current trend, geo and sleep time information) for the authenticating user.


.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-settings

#>
    [CmdletBinding()]
    Param(
        
    )
    Begin {

        [string]$Method      = 'GET'
        [string]$Resource    = '/account/settings'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/account/settings.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
