function Get-TwitterWelcome_Messages {

<#
.SYNOPSIS
    Welcome Messages

.DESCRIPTION
    GET direct_messages/welcome_messages/list
    
    Returns a list of Welcome Messages.

.PARAMETER count (optional)
    

.PARAMETER cursor (optional)
    

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/direct-messages/welcome-messages/api-reference/list-welcome-messages

#>
    [CmdletBinding()]
    Param(
        [string]$count (optional),
        [string]$cursor (optional)
    )
    Begin {

        [string]$Method      = 'GET'
        [string]$Resource    = '/direct_messages/welcome_messages/list'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/direct_messages/welcome_messages/list.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
