function Get-TwitterApplication_RateLimitStatus {
<#
.SYNOPSIS
    Get app rate limit status

.DESCRIPTION
    GET application/rate_limit_status
    
    Returns the current rate limits for methods belonging to the specified resource families.
    
    Each API resource belongs to a "resource family" which is indicated in its method documentation. The method's resource family can be determined from the first component of the path after the resource version.
    
    This method responds with a map of methods belonging to the families specified by the resources parameter, the current remaining uses for each of those resources within the current rate limiting window, and their expiration time in epoch time. It also includes a rate_limit_context field that indicates the current access token or application-only authentication context.
    
    You may also issue requests to this method without any parameters to receive a map of all rate limited GET methods. If your application only uses a few of methods, you should explicitly provide a resources parameter with the specified resource families you work with.
    
    When using application-only auth, this method's response indicates the application-only auth rate limiting context.
    
    Read more about API Rate Limiting and review the limits.

.PARAMETER resources
    A comma-separated list of resource families you want to know the current rate limit disposition for. For best performance, only specify the resource families pertinent to your application. See API Rate Limiting for more information.

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status

#>
    [CmdletBinding()]
    Param(
        [string]$resources
    )
    Begin {

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

        [string]$Method      = 'GET'
        [string]$Resource    = '/application/rate_limit_status'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/application/rate_limit_status.json'

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Method $Method -ResourceUrl $ResourceUrl -Resource $Resource -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
