function Get-TwitterHelp_Tos {
<#
.SYNOPSIS
    Get Twitter's terms of service

.DESCRIPTION
    GET help/tos
    
    Returns the Twitter Terms of Service. Note: these are not the same as the Developer Policy.


.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/developer-utilities/terms-of-service/api-reference/get-help-tos

#>
    [CmdletBinding()]
    Param(
        
    )
    Begin {

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

        [string]$Method      = 'GET'
        [string]$Resource    = '/help/tos'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/help/tos.json'

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Method $Method -ResourceUrl $ResourceUrl -Resource $Resource -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
