function Get-TwitterGeo_Id_PlaceId {

<#
.SYNOPSIS
    Get information about a place

.DESCRIPTION
    GET geo/id/:place_id
    
    Returns all the information about a known place.

.PARAMETER place_id
    A place in the world. These IDs can be retrieved from geo/reverse_geocode.

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/geo/place-information/api-reference/get-geo-id-place_id

#>
    [CmdletBinding()]
    Param(
        [string]$place_id
    )
    Begin {

        [string]$Method      = 'GET'
        [string]$Resource    = '/geo/id/:place_id'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/geo/id/:place_id.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
