function Get-TwitterFriendships_NoRetweets_Ids {

<#
.SYNOPSIS
    Follow, search, and get users

.DESCRIPTION
    GET friendships/no_retweets/ids
    
    Returns a collection of user_ids that the currently authenticated user does not want to receive retweets from.
    
    Use POST friendships / update to set the "no retweets" status for a given user account on behalf of the current user.

.PARAMETER stringify_ids
    Some programming environments will not consume Twitter IDs due to their size. Provide this option to have IDs returned as strings instead. Read more about Twitter IDs. This parameter is important to use in Javascript environments.

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-no_retweets-ids

#>
    [CmdletBinding()]
    Param(
        [string]$stringify_ids
    )
    Begin {

        [string]$Method      = 'GET'
        [string]$Resource    = '/friendships/no_retweets/ids'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/friendships/no_retweets/ids.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
