function Get-TwitterUsers_Suggestions_Slug_Members {

<#
.SYNOPSIS
    Follow, search, and get users

.DESCRIPTION
    GET users/suggestions/:slug/members
    
    Access the users in a given category of the Twitter suggested user list and return their most recent status if they are not a protected user.

.PARAMETER slug
    The short name of list or a category

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-suggestions-slug-members

#>
    [CmdletBinding()]
    Param(
        [string]$slug
    )
    Begin {

        [string]$Method      = 'GET'
        [string]$Resource    = '/users/suggestions/:slug/members'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/users/suggestions/:slug/members.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
