function Get-TwitterHelp_Privacy {
<#
.SYNOPSIS
    Get Twitter's privacy policy

.DESCRIPTION
    GET help/privacy
    
    Returns Twitter's Privacy Policy.


.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/developer-utilities/privacy-policy/api-reference/get-help-privacy

#>
    [CmdletBinding()]
    Param(
        
    )
    Begin {

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

        [string]$Method      = 'GET'
        [string]$Resource    = '/help/privacy'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/help/privacy.json'

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Method $Method -ResourceUrl $ResourceUrl -Resource $Resource -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
