function Get-TwitterFriendships_Show {
<#
.SYNOPSIS
    Follow, search, and get users

.DESCRIPTION
    GET friendships/show
    
    Returns detailed information about the relationship between two arbitrary users.

.PARAMETER source_id
    The user_id of the subject user.

.PARAMETER source_screen_name
    The screen_name of the subject user.

.PARAMETER target_id
    The user_id of the target user.

.PARAMETER target_screen_name
    The screen_name of the target user.

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show

#>
    [CmdletBinding()]
    Param(
        [string]$source_id,
        [string]$source_screen_name,
        [string]$target_id,
        [string]$target_screen_name
    )
    Begin {

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

        [string]$Method      = 'GET'
        [string]$Resource    = '/friendships/show'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/friendships/show.json'

    }
    Process {

        # Find & Replace any ResourceUrl parameters.
        $UrlParameters = [regex]::Matches($ResourceUrl, '(?<!\w):\w+')
        ForEach ($UrlParameter in $UrlParameters) {
            $UrlParameterValue = $Parameters["$($UrlParameter.Value.TrimStart(":"))"]
            $ResourceUrl = $ResourceUrl -Replace $UrlParameter.Value, $UrlParameterValue
        }

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Method $Method -ResourceUrl $ResourceUrl -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
