function Remove-TwitterCustomProfiles_Destroy {
<#
.SYNOPSIS
    Custom profiles

.DESCRIPTION
    DELETE custom_profiles/destroy.json
    
    Deletes a custom profile that was created with POST custom_profiles/new.json.

.PARAMETER id (required)
    

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/direct-messages/custom-profiles/api-reference/delete-profile

#>
    [CmdletBinding()]
    Param(
        [string]$id
    )
    Begin {

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

        [string]$Method      = 'DELETE'
        [string]$Resource    = '/custom_profiles/destroy'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/custom_profiles/destroy.json'

    }
    Process {

        # Find & Replace any ResourceUrl parameters.
        $UrlParameters = [regex]::Matches($ResourceUrl, '(?<!\w):\w+')
        ForEach ($UrlParameter in $UrlParameters) {
            $UrlParameterValue = $Parameters["$($UrlParameter.Value.TrimStart(":"))"]
            $ResourceUrl = $ResourceUrl -Replace $UrlParameter.Value, $UrlParameterValue
        }

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Method $Method -ResourceUrl $ResourceUrl -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
