function Send-TwitterFriendships_Update {

<#
.SYNOPSIS
    Follow, search, and get users

.DESCRIPTION
    POST friendships/update
    
    Enable or disable Retweets and device notifications from the specified user.

.PARAMETER screen_name
    The screen name of the user being followed.

.PARAMETER user_id
    The ID of the user being followed.

.PARAMETER device
    Enable/disable device notifications from the target user.

.PARAMETER retweets
    Enable/disable Retweets from the target user.

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-update

#>
    [CmdletBinding()]
    Param(
        [string]$screen_name,
        [string]$user_id,
        [string]$device,
        [string]$retweets
    )
    Begin {

        [string]$Method      = 'POST'
        [string]$Resource    = '/friendships/update'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/friendships/update.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
