function Send-TwitterRead_Receipt {

<#
.SYNOPSIS
    Typing indicator and read receipts

.DESCRIPTION
    POST direct_messages/mark_read
    
    Marks a message as read in the recipient’s Direct Message conversation view with the sender.

.PARAMETER last_read_event_id (required)
    

.PARAMETER recipient_id (required)
    

.PARAMETER 204
    

.PARAMETER 400
    

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/direct-messages/typing-indicator-and-read-receipts/api-reference/new-read-receipt

#>
    [CmdletBinding()]
    Param(
        [string]$last_read_event_id,
        [string]$recipient_id,
        [string]$204,
        [string]$400
    )
    Begin {

        [string]$Method      = 'POST'
        [string]$Resource    = '/direct_messages/mark_read'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/direct_messages/mark_read.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | ForEach-Object { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Method $Method -ResourceUrl $ResourceUrl -Resource $Resource -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
