function Send-TwitterFavorites_Create {

<#
.SYNOPSIS
    Post, retrieve and engage with Tweets

.DESCRIPTION
    POST favorites/create
    
    Note: favorites are now known as likes.
    
    Favorites (likes) the Tweet specified in the ID parameter as the authenticating user. Returns the favorite Tweet when successful.
    
    The process invoked by this method is asynchronous. The immediately returned Tweet object may not indicate the resultant favorited status of the Tweet. A 200 OK response from this method will indicate whether the intended action was successful or not.

.PARAMETER id
    The numerical ID of the Tweet to like.

.PARAMETER include_entities
    The entities node will be omitted when set to false .

.NOTES
    This helper function was generated by the information provided here:
    https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-favorites-create

#>
    [CmdletBinding()]
    Param(
        [string]$id,
        [string]$include_entities
    )
    Begin {

        [string]$Method      = 'POST'
        [string]$Resource    = '/favorites/create'
        [string]$ResourceUrl = 'https://api.twitter.com/1.1/favorites/create.json'

        [hashtable]$Parameters = $PSBoundParameters
                   $CmdletBindingParameters | % { $Parameters.Remove($_) }

    }
    Process {

        If (-Not $OAuthSettings) { $OAuthSettings = Get-TwitterOAuthSettings -Resource $Resource }
        Invoke-TwitterAPI -Resource $Resource -Method $Method -Parameters $Parameters -OAuthSettings $OAuthSettings

    }
    End {

    }
}
